library(dplyr)
library(DT)
library(fresh)
library(ggplot2)
library(ggrepel)
library(readxl)
library(shinyBS)
library(shinydashboard)
library(shinydashboardPlus)
library(shiny.i18n)
library(shinyWidgets)
library(shinycssloaders)

source('home.R')
source('load.R')
source('FPI.R')
source('dynamics.R')
source('results.R')

for (fl in list.files("./Source")) source(file.path("./Source", fl))
